version: '3.7'
services:
  rails:
    build: &rails_build
      context: .
    volumes: &rails_volumes
      - .:/app
    env_file: &env
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/rails_dev
    ports:
     - "3000:3000"
  webpacker:
    build: *rails_build
    volumes: *rails_volumes
    env_file: *env
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  postgres:
    image: "postgres:10.3-alpine"
    ports: ["5432:5432"]
    volumes:
      - $HOME/docker_data/rails_new:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rails_dev
      - POSTGRES_PASSWORD=password
